version: '3.1'
services:
  web_api:
    build: .
    image: resize_api:latest
    restart: always
    container_name: resize_api
    environment:
      - CELERY_BROKER_URL=redis://redis
      - CELERY_RESULT_BACKEND=redis://redis
    ports:
      - "8080:8080"
    links:
      - redis
    depends_on:
      - redis
      - celery_workers

  celery_workers:
    build: celery_queue/.
    restart: always
    container_name: resize_celery
    environment:
      - CELERY_BROKER_URL=redis://redis
      - CELERY_RESULT_BACKEND=redis://redis
      - C_FORCE_ROOT=true
    links:
      - redis
    depends_on:
      - redis

  redis:
    image: redis:5.0.3
    container_name: resize_redis
    restart: always
#    ports:
#      - "6379:6379"
